import React, { useRef } from 'react';
import { StoryState } from '../types';
import QuizModule from './QuizModule';

interface StoryDisplayProps {
  story: StoryState;
  onReset: () => void;
}

const StoryDisplay: React.FC<StoryDisplayProps> = ({ story, onReset }) => {
  const contentRef = useRef<HTMLDivElement>(null);

  const handleCopy = () => {
    const fullText = `${story.title}\n\n${story.content}`;
    navigator.clipboard.writeText(fullText);
    alert('Story copied to clipboard!');
  };

  const handleSave = () => {
    const fullText = `${story.title}\n\n${story.content}`;
    const blob = new Blob([fullText], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${story.title.replace(/\s+/g, '_')}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="w-full max-w-4xl mx-auto animate-fade-in">
      <div className="bg-dark-card border border-white/10 rounded-2xl shadow-2xl overflow-hidden backdrop-blur-sm">
        {/* Header Actions */}
        <div className="bg-white/5 p-4 flex justify-between items-center border-b border-white/10">
          <button 
            onClick={onReset}
            className="flex items-center space-x-2 text-sm text-gray-400 hover:text-white transition-colors"
          >
            <svg xmlns="http://www.w3.org/2000/svg" className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10 19l-7-7m0 0l7-7m-7 7h18" />
            </svg>
            <span>Create New Story</span>
          </button>
          <div className="flex space-x-2">
            <button 
              onClick={handleSave}
              className="px-3 py-1.5 rounded-lg bg-white/10 hover:bg-white/20 text-sm font-medium text-primary-start transition-all"
            >
              Save Text
            </button>
            <button 
              onClick={handleCopy}
              className="px-3 py-1.5 rounded-lg bg-primary-start hover:bg-primary-end text-dark-bg text-sm font-bold transition-all shadow-[0_0_10px_rgba(129,162,255,0.3)]"
            >
              Share / Copy
            </button>
          </div>
        </div>

        {/* Story Content & Quiz */}
        <div 
          ref={contentRef}
          className="p-8 md:p-12 max-h-[85vh] overflow-y-auto story-scroll bg-gradient-to-b from-dark-card to-black/40"
        >
          <h2 className="text-3xl md:text-4xl font-display font-bold text-center mb-8 bg-gradient-to-r from-primary-start to-primary-end bg-clip-text text-transparent">
            {story.title}
          </h2>
          <div className="prose prose-invert prose-lg max-w-none">
            {story.content.split('\n').map((paragraph, idx) => (
              paragraph.trim() && <p key={idx} className="mb-4 leading-relaxed text-gray-200">{paragraph}</p>
            ))}
          </div>
          
          <div className="mt-8 text-center mb-4">
            <p className="text-sm text-gray-500 italic">
              Generated by StorySpark AI • {new Date(story.timestamp).toLocaleDateString()}
            </p>
          </div>

          {/* Quiz Module */}
          {story.quiz && story.quiz.length > 0 && (
             <QuizModule questions={story.quiz} />
          )}

        </div>
      </div>
      
      {/* Post-read call to action */}
      <div className="mt-6 text-center">
        <button
          onClick={() => contentRef.current?.scrollTo({ top: 0, behavior: 'smooth' })}
          className="text-primary-start hover:text-primary-end text-sm font-medium underline decoration-primary-start/50 underline-offset-4"
        >
          Return to Top
        </button>
      </div>
    </div>
  );
};

export default StoryDisplay;
